export const ARRHENIUS_EA_J_PER_MOL = 52_844;
export const GAS_CONSTANT_R_J_PER_MOL_K = 8.314;
export const REFERENCE_TEMP_C = 25;
export const REFERENCE_TEMP_K = REFERENCE_TEMP_C + 273.15;

export const STARTER_FACTOR_REFERENCE_PCT = 20;

export const TARGET_UNITS_MIN = 7.5;
export const TARGET_UNITS_MAX = 12.5;
export const TARGET_UNITS_SLOPE_PER_PH = 5;
export const TARGET_UNITS_INTERCEPT = 25;

export const SAFE_FLOOR_INPUT_MIN_C = 20;
export const SAFE_FLOOR_INPUT_MAX_C = 24;
export const SAFE_FLOOR_MIN_PCT = 15;
export const SAFE_FLOOR_MAX_PCT = 30;
export const SAFE_FLOOR_SPAN_C = SAFE_FLOOR_INPUT_MAX_C - SAFE_FLOOR_INPUT_MIN_C;

export const DEFAULT_ROOM_OFFSET_C = 3.0;
